
import java.util.Set;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Usuario
 */
public class jfrmConversor extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jfrmConversor.class.getName());

    /**
     * Creates new form jfrmConversor
     */
    public jfrmConversor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jtfMoneda = new javax.swing.JTextField();
        jtfCantidad = new javax.swing.JTextField();
        jtfPais = new javax.swing.JTextField();
        jbtnConvertir = new javax.swing.JButton();
        jbtnLimpiar = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("DATOS");

        jLabel3.setText("Nombre del Usuario");

        jLabel4.setText("Pais Destino");

        jLabel5.setText("Cantidad en Quetzales");

        jLabel6.setText("Tipo de Conversion");

        jLabel7.setText("CONTROL");

        jtfNombre.setText("                   ");

        jtfMoneda.setText("                   ");
        jtfMoneda.addActionListener(this::jtfMonedaActionPerformed);

        jtfCantidad.setText("                   ");

        jtfPais.setText("                   ");
        jtfPais.addActionListener(this::jtfPaisActionPerformed);

        jbtnConvertir.setText("CONVERTIR");
        jbtnConvertir.addActionListener(this::jbtnConvertirActionPerformed);

        jbtnLimpiar.setText("LIMPIAR");
        jbtnLimpiar.addActionListener(this::jbtnLimpiarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(204, 204, 204))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel2)
                                .addGap(80, 80, 80))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6)
                                            .addComponent(jbtnConvertir))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(59, 59, 59))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtfCantidad, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtfNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtfMoneda, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtfPais, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnLimpiar)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnLimpiar)
                    .addComponent(jbtnConvertir))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPaisActionPerformed

    private void jtfMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMonedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfMonedaActionPerformed

    private void jbtnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConvertirActionPerformed
        // TODO add your handling code here:
        
        String nombre = jtfNombre.getText().trim();
        String strCant = jtfCantidad.getText().trim();
        String moneda = jtfMoneda.getText().trim();
        String pais = jtfPais.getText().trim();
        
        if(nombre.isEmpty())
        if(strCant.isEmpty())
        if(moneda.isEmpty())
        if(pais.isEmpty())
        { 
        JOptionPane.showMessageDialog(this,
                "Complete todos los campos",
                "Campos vacios",
                JOptionPane.WARNING_MESSAGE);
        return;
        }
        
        double cantidad;
        try{
            cantidad= Double.parseDouble(strCant);
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this,
                    "La cantidad debe ser un numero",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
         return;
        }
        double resultado;
        String simbolo;
        
        if (moneda.equals("dolar")) {
            resultado = cantidad /7.80;
            simbolo = "$";
        } else if (moneda.equals("euro")){
            resultado = cantidad / 8.50;
            simbolo = "E";
        } else if (moneda.equals("peso")){
            resultado = cantidad/ 0.40;
            simbolo = "MX";
        } else{
            JOptionPane.showMessageDialog(this,
                    "Moneda Invalidad. Use: Dolar,Euro o peso",
                    "ERROR",
                    JOptionPane.ERROR_MESSAGE);
         return;
        }
        JOptionPane.showMessageDialog(this,
                "=======CONVERSION=======\n" +
                "Usuario:"                 +nombre+ "\n"+
                "Pais destino:"           +pais+ "\n" +
                "Moneda seleccionada:"     +moneda+"\n"+
                "Cantidad en quetzales:Q"  + String.format("%2f",cantidad)+ "\n"+
                 "Resultado convertido:"    +simbolo+ String.format("%2f",resultado),
                "Resultado",
                JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_jbtnConvertirActionPerformed

    private void jbtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimpiarActionPerformed
        // TODO add your handling code here:
        jtfNombre.setText("");
        jtfCantidad.setText("");
        jtfMoneda.setText("");
        jtfPais.setText("");
        jtfNombre.requestFocus();
    }//GEN-LAST:event_jbtnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jfrmConversor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbtnConvertir;
    private javax.swing.JButton jbtnLimpiar;
    private javax.swing.JTextField jtfCantidad;
    private javax.swing.JTextField jtfMoneda;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfPais;
    // End of variables declaration//GEN-END:variables
}
